- setup.cake
Exclude Cake.Issues.Testing from code coverage
> Exclude Cake.Issues.Testing from code coverage

- src/Cake.Issues.InspectCode.Tests/Cake.Issues.InspectCode.Tests.csproj
- src/Cake.Issues.InspectCode.Tests/packages.config
- src/Cake.Issues.InspectCode/Cake.Issues.InspectCode.csproj
- src/Cake.Issues.InspectCode/InspectCodeIssuesAliases.cs
- src/Cake.Issues.InspectCode/packages.config
Add InspectCodeIssuesProviderTypeName alias.
Fixes #3
> (GH-3) Add InspectCodeIssuesProviderTypeName alias

- cake.config
- setup.cake
- tools/packages.config
Update to Cake 0.23.0 for compatibility with latest Cake.Recipe
Fixes #10
> (GH-10) Upgrade to Cake 0.23.0

- src/Cake.Issues.InspectCode.Tests/Cake.Issues.InspectCode.Tests.csproj
- src/Cake.Issues.InspectCode.Tests/packages.config
- src/Cake.Issues.InspectCode/Cake.Issues.InspectCode.csproj
- src/Cake.Issues.InspectCode/packages.config
Build against Cake 0.26 and Cake.Issues 0.2.0
Also updates XUnit to 2.3.1 and Shouldly to 3.0.0
Fixes #12
Fixes #14
> Update to Cake.Issues 0.2.0

- src/Cake.Issues.InspectCode.Tests/Cake.Issues.InspectCode.Tests.csproj
- src/Cake.Issues.InspectCode.Tests/packages.config
- src/Cake.Issues.InspectCode/Cake.Issues.InspectCode.csproj
- src/Cake.Issues.InspectCode/InspectCodeIssuesProvider.cs
- src/Cake.Issues.InspectCode/packages.config
Update to Cake.Issues 0.3.0
Fixes #16
> (GH-16) Update to Cake.Issues 0.3.0

- src/Cake.Issues.InspectCode.Tests/InspectCodeIssuesProviderTests.cs
- src/Cake.Issues.InspectCode/InspectCodeIssuesProvider.cs
Set priority and priorityName based on severity of issue type
Fixes #4
> (GH-4) Set priority

- tools/packages.config
Build with Cake 0.29.0
Fixes #22
> (GH-22) Build with Cake 0.29.0

- src/Cake.Issues.InspectCode.Tests/Cake.Issues.InspectCode.Tests.csproj
- src/Cake.Issues.InspectCode.Tests/packages.config
- src/Cake.Issues.InspectCode/Cake.Issues.InspectCode.csproj
- src/Cake.Issues.InspectCode/packages.config
Update Cake.Issues to 0.4.0-beta.1
Fixes #25
> (GH-25) Update Cake.Issues to 0.4.0-beta.1

- src/Cake.Issues.InspectCode.Tests/InspectCodeIssuesProviderTests.cs
- src/Cake.Issues.InspectCode/InspectCodeIssuesProvider.cs
Read and provide project name
Fixes #13
> (GH-13) Read project name

- src/Cake.Issues.InspectCode.Tests/Cake.Issues.InspectCode.Tests.csproj
- src/Cake.Issues.InspectCode.Tests/ExtensionsTests.cs
- src/Cake.Issues.InspectCode.Tests/InspectCodeIssuesProviderFixture.cs
- src/Cake.Issues.InspectCode.Tests/InspectCodeIssuesProviderTests.cs
- src/Cake.Issues.InspectCode.Tests/InspectCodeIssuesSettingsTests.cs
- src/Cake.Issues.InspectCode.Tests/packages.config
- src/Cake.Issues.InspectCode/Cake.Issues.InspectCode.csproj
- src/Cake.Issues.InspectCode/InspectCodeIssuesAliases.cs
- src/Cake.Issues.InspectCode/InspectCodeIssuesProvider.cs
- src/Cake.Issues.InspectCode/InspectCodeIssuesSettings.cs
- src/Cake.Issues.InspectCode/packages.config
Update to Cake.Issues 0.5.0-beta.2 and use new issue provider infrastructure
Fixes #27
> (GH-27) Update to Cake.Issues 0.5.0-beta.2

- src/Cake.Issues.InspectCode.Tests/Cake.Issues.InspectCode.Tests.csproj
- src/Cake.Issues.InspectCode.Tests/packages.config
- src/Cake.Issues.InspectCode/Cake.Issues.InspectCode.csproj
- src/Cake.Issues.InspectCode/packages.config
Update to Cake.Issues 0.6.0 Beta 1
Fixes #30
> (GH-30) Update to Cake.Issues 0.6.0 Beta 1

- src/Cake.Issues.InspectCode.Tests/Cake.Issues.InspectCode.Tests.csproj
> Update XUnit to 2.4.1

- .appveyor.yml
Remove no longer existing folder from AppVeyor cache
> Remove no longer existing folder from AppVeyor cache

- src/Cake.Issues.InspectCode/Cake.Issues.InspectCode.csproj
> Update FxCop analyzers

- src/Cake.Issues.InspectCode.Tests/Cake.Issues.InspectCode.Tests.csproj
- src/Cake.Issues.InspectCode/Cake.Issues.InspectCode.csproj
Build against Cake 0.33.0
Fixes #56
> (GH-56) Build against Cake 0.33.0

- src/Cake.Issues.InspectCode.Tests/Cake.Issues.InspectCode.Tests.csproj
- src/Cake.Issues.InspectCode.Tests/InspectCodeIssuesProviderTests.cs
- src/Cake.Issues.InspectCode.Tests/InspectCodeIssuesSettingsTests.cs
- src/Cake.Issues.InspectCode/Cake.Issues.InspectCode.csproj
Update to Cake.Issues 0.7.0
Fixes #57
> (GH-57) Update to Cake.Issues 0.7.0

- README.md
- nuspec/nuget/Cake.Issues.InspectCode.nuspec
Website changed to cakeissues.net
Fixes #78
> (GH-78) Change website to cakeissues.net

- src/Cake.Issues.InspectCode/InspectCodeIssuesAliases.cs
- src/Cake.Issues.InspectCode/InspectCodeIssuesSettings.cs
> Fix comment

- README.md
> Fix AppVeyor links

- src/Cake.Issues.InspectCode/InspectCodeIssuesAliases.cs
> Fix typo in comment

- docs/features.md
- src/Cake.Issues.InspectCode.Tests/Cake.Issues.InspectCode.Tests.csproj
- src/Cake.Issues.InspectCode/Cake.Issues.InspectCode.csproj
Update to Cake.Issues 0.9.0 Beta 2
Fixes #126
> (GH-126) Update to Cake.Issues 0.9.0 Beta 2

- src/Cake.Issues.InspectCode.Tests/Cake.Issues.InspectCode.Tests.csproj
- src/Cake.Issues.InspectCode/Cake.Issues.InspectCode.csproj
Build against Cake.Issues 1.0 beta 1
> Build against Cake.Issues 1.0 beta 1

- src/Cake.Issues.InspectCode.Tests/Cake.Issues.InspectCode.Tests.csproj
- src/Cake.Issues.InspectCode/Cake.Issues.InspectCode.csproj
Builds against Cake 2.0
Fixes #188 
Fixes #190
> (GH-188) Build against Cake 2.0

- .github/dependabot.yml
Update Depandabot configuration to ignore Cake 2.x
> Update Depandabot configuration to ignore Cake 2.x

- src/Cake.Issues.InspectCode.Tests/InspectCodeIssuesProviderTests.cs
- src/Cake.Issues.InspectCode/InspectCodeIssuesProvider.cs
Returns rule description as rule name
Fixes #197
> (GH-197) Support rule name

- .appveyor.yml
- azure-pipelines.yml
- nuspec/nuget/Cake.Issues.InspectCode.nuspec
- src/Cake.Issues.InspectCode.Tests/Cake.Issues.InspectCode.Tests.csproj
- src/Cake.Issues.InspectCode/Cake.Issues.InspectCode.csproj
Updates target frameworks to .NET 6 and .NET 7.
Fixes #214
> (GH-214) Update target frameworks

- src/Cake.Issues.InspectCode.Tests/Cake.Issues.InspectCode.Tests.csproj
- src/Cake.Issues.InspectCode/Cake.Issues.InspectCode.csproj
Builds against Cake 3.0 and Cake.Issues 3.0 Beta 1
Fixes #215 
Fixes #216
> Update for Cake 3.0 and Cake.Issues 3.0

- src/.editorconfig
- src/Cake.Issues.InspectCode.Tests/ExtensionsTests.cs
- src/Cake.Issues.InspectCode.Tests/InspectCodeIssuesProviderTests.cs
- src/Cake.Issues.InspectCode.Tests/InspectCodeIssuesSettingsTests.cs
- src/Cake.Issues.InspectCode.sln.DotSettings
- src/Cake.Issues.InspectCode/InspectCodeIssuesProvider.cs
> Fix linting issues

- recipe.cake
Updates build to use Cake.Recipe 3.0.1
> Update Cake.Recipe to 3.0.1

- cake.config
Removes no longer required Cake configuration file
> Remove no longer required Cake config file

- .appveyor.yml
- azure-pipelines.yml
- nuspec/nuget/Cake.Issues.InspectCode.nuspec
- src/Cake.Issues.InspectCode/Cake.Issues.InspectCode.csproj
Multi-Target .NET 6, .NET 7 & .NET 8
Fixes #259
> Multi-Target .NET 6, .NET 7 & .NET 8

- src/Cake.Issues.InspectCode.Tests/Cake.Issues.InspectCode.Tests.csproj
- src/Cake.Issues.InspectCode/Cake.Issues.InspectCode.csproj
Update to Cake.Issues 4.0.0-beta0001
Fixes #261
> Update to Cake.Issues 4.0.0-beta0001

- .appveyor.yml
Updates .NET SDK version for AppVeyor
> Update .NET SDK version for AppVeyor

- src/Cake.Issues.InspectCode/InspectCodeIssuesProvider.cs
- src/Directory.Build.props
> Use latest C# version
